when:
  event: [push, cron, pull_request, manual]

steps:
  - name: Debian
    image: debian:13
    pull: true
    commands:
      - apt update && apt full-upgrade && apt install -y ocaml libfindlib-ocaml-dev libcontainers-ocaml-dev ocaml-dune
      - dune build
