when:
  event: [push, cron, pull_request, manual]

steps:
  - name: Build on Debian
    image: debian:13
    pull: true
    commands:
      - apt update && apt full-upgrade -y
      - apt install -y ocaml libfindlib-ocaml-dev ocaml-dune menhir
      - dune build
      - dune exec ollisp
