when:
  event: [push, cron, pull_request, manual]

steps:
  - name: Build on NixOS
    image: nixos/nix:latest
    pull: true
    commands:
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes build
      - ./result/bin/ollisp
