when:
  event: [push, cron, pull_request, manual]

steps:
  - name: Build Nightly Artifact
    image: ocaml/opam:debian-11-ocaml-5.4
    commands:
      - opam install . --deps-only
      - opam exec -- dune build
      - mkdir -p dist
      - opam exec -- dune install --prefix=$(pwd)/dist

      - tar czvf ollisp-nightly.tar.gz -C dist .
  - name: Publish to Gitea
    image: curlimages/curl
    environment:
      GITEA_TOKEN:
        from_secret: package_token
    commands:
      - curl -v --user "$CI_REPO_OWNER:$GITEA_TOKEN" --upload-file my-lang-nightly-linux-amd64.tar.gz $CI_FORGE_URL/api/packages/$CI_REPO_OWNER/generic/olisp/nightly/ollisp-nightly-amd64.tar.gz?duplicate_upgrade=true
  
